name: "Generate a new Rails API"

on:
  workflow_dispatch:
    inputs:
      RUBY_VERSION:
        required: true
      RAILS_VERSION:
        required: true
      TEST_BOOL:
        required: true

jobs:
  rails-new:
    runs-on: ubuntu-latest
    steps:

      - name: echo the bool
        run: echo ${{ github.event.inputs.TEST_BOOL }}
      
      - name: checkout stack template
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: setup ruby ${{ github.event.inputs.RUBY_VERSION }} 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ github.event.inputs.RUBY_VERSION }}
          bundler-cache: true
      
      - name: generate a new rails project
        run: |
          gem install rails --version ${{ github.event.inputs.RAILS_VERSION }} --no-document
          rails new . --rc=.railsrc
          rm -f .railsrc

      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "generated a new rails api"
          branch: generated-project
          title: "Generate a new rails API project and workflows"
          body: |
            This PR was generated by https://github.com/gscho/rails-api-heroku-stack
          reviewers: ${{ github.actor }}