name: "Create a new Rails API"

on:
  workflow_dispatch:
    inputs:
      RUBY_VERSION:
        required: true
      
      RAILS_VERSION:
        required: true

jobs:
  stack-initialization:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout stack template
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: setup ruby ${{ github.event.inputs.RUBY_VERSION }} 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ github.event.inputs.RUBY_VERSION }}
          bundler-cache: true
      
      - name: rails new
        run: |
          gem install rails --version ${{ github.event.inputs.RAILS_VERSION }} --no-document
          rails new . --rc=./.railsrc
          ls -la