name: "Generate a New Rails API"

on:
  workflow_dispatch:
    inputs:
      RUBY_VERSION:
        required: true
      RAILS_VERSION:
        required: true
      RAILS_RC_URL:
        required: false
      HEROKU_APP_NAME:
        required: true

jobs:
  rails-new:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout stack template
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: substitute user inputs in the cd.yml
        uses: microsoft/variable-substitution@v1 
        with:
          files: '.github/workflows/cd.yml'
        env:
          ___RUBY_VERSION___: '${{ github.event.inputs.RUBY_VERSION }}'
          ___HEROKU_APP_NAME___: '${{ github.event.inputs.HEROKU_APP_NAME }}'
      
      - name: setup ruby ${{ github.event.inputs.RUBY_VERSION }} 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ github.event.inputs.RUBY_VERSION }}
          bundler-cache: true
      
      - name: generate a new rails project
        run: |
          gem install rails --version ${{ github.event.inputs.RAILS_VERSION }} --no-document
          rails new . --rc=.railsrc
          rm -f .railsrc

      - name: create a CODEOWNERS file
        run: echo @"${{ github.actor }}" > CODEOWNERS

      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "generated a new rails api"
          branch: generated-project
          title: "Generate a new rails API project and workflows"
          body: |
            This PR was generated by https://github.com/gscho/rails-api-heroku-stack
          reviewers: ${{ github.actor }}